### PR TITLE
Update pinning

### PR DESCRIPTION
**Pull request by dpryan79**
This (A) updates the conda-forge-pinnings to the (currently) most recent version and adds a `bioconda-utils update-pinnings` function that can be used to bump a given package and all dependencies as appropriate if and only if they are affected by the change in pinnings.

I also changed `bioconda-utils dag` so that it will show the DAG of all dependencies of the package(s) specified. The previous behavior was to filter the DAG for only the packages specified, which tended to leave a bunch of singletons and was probably now what people really wanted.

### CODE REVIEW

**Comment by dpryan79** [comment]
This PR now also:

 - Pins the docker version to a known functional docker container (before conda-forge added conda 4.6 to their containers)
 - Fixes the nightly builds such by adding bioconda back to the list of channels checked (so nightly doesn't keep trying to build and upload everything).

**Comment by dpryan79** [comment]
@bioconda/core Can someone else have a look at this? This should resolve a number of issues that have popped up over the last couple days too (borked versions of conda in the docker container and nightly builds trying to build and upload everything).

**Comment by bgruening** [comment]
Already on it ... testing the branch. From looking at the code it looks good.

**Comment by bgruening** [comment]
Thanks @dpryan79! This fixes a lot of recent issues.

**Pull request merged**
