### PR TITLE
fix: adds alternate lookup if base lookup fails

### PR DESCRIPTION
**Pull request by holtjma**
This is a first pass attempt at fixing #895.

Main changes are updating the GithubRelease hoster to look for alternate paths via the GitHub API.  The API sends a JSON response (example: https://api.github.com/repos/PacificBiosciences/HiPhase/releases) that contains each release along with a list of assets.  The assets are searched for files that match the provides pattern.  Currently, this first pass puts this as a backup to the main one (which I think is always failing now).  I also did not update the tests, I think someone may have a better idea of how to do that.  Happy to help push this further, but wanted to get the ball rolling.

### CODE REVIEW

**Comment by dpryan79** [comment]
Wow, yeah that DESeq2 failure is definitely not your fault, I suspect bioconductor has removed the file.

**Comment by dpryan79** [comment]
@johanneskoester @mbargull Any thoughts on this PR?

**Comment by holtjma** [comment]
@johanneskoester @mbargull @dpryan79 

Circling back on this, any thoughts on the functional changes and/or fixing the test?  Happy to look into making the changes, just need to know what's missing here.

**Review by johanneskoester — APPROVED** [review]
Looks good to me. I've updated with the master branch, which should fix the test issue with deseq if I remember correctly.

**Comment by holtjma** [comment]
@johanneskoester I fixed that previous error by just bumping the versions (assuming this is fine).  However, there's some new error in the OSX tests.  I took a quick look, but it's not obvious to me what's happening there.

**Pull request merged**
