### PR TITLE
chore: Automate releases and changelog with release-please

### PR DESCRIPTION
**Pull request by johanneskoester**

### CODE REVIEW

**Comment by epruesse** [comment]
LGTM but maybe have someone check who understand this stuff better than me.

**Comment by dpryan79** [comment]
Is the build-and-push-image workflow still doing anything useful? It seems to now just build and test when a release is published, which is a bit late if it's not also going to push the image. Maybe just remove that workflow.

**Comment by johanneskoester** [comment]
Good point. It also tests the image building though, but I have cleaned it up further now.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
@johanneskoester Merge at your leisure :)

**Pull request merged**
