### PR TITLE
docs: rename recipe index to package index + minor layout fixes

### PR DESCRIPTION
**Pull request by mbargull**
I'll post screenshots for comparison in a bit (building docs locally right now..).

### CODE REVIEW

**Comment by mbargull** [comment]
before:
image
image
image

**Comment by mbargull** [comment]
after:
image
image
image
image

**Comment by dpryan79** [comment]
Nice!

**Comment by mbargull** [comment]
Oh, I just noticed that the `Required By:` doesn't work anymore... Maybe I have to do something different than just adding `:noindex:` to the recipes.

**Comment by mbargull** [comment]
> Oh, I just noticed that the `Required By:` doesn't work anymore... 

Nvm. I built the docs locally with `-j8` and that didn't yield the `Required By:` entries. But with `-j1` it works. I'll just add a note in `build-docs.sh`. 

----
I also added a commit to put versions/constraints in `<code>` blocks: IMHO, that makes things slightly more readable and it also fixed reST issues with dependencies like `python_abi 3.6.* *cp36m` that have asterisks in them (that commit also does `.replace(" ", "\xa0")` for those entries which might also fixed things -- still, code blocks make them more readable, anyway).

before:
image
after:
image

image

**Comment by mbargull** [comment]
I'll merge once https://github.com/bioconda/bioconda-recipes/pull/22526 is in to check if the newly built package index also has the `pmid`/`rrid` identifiers linked properly (works locally, but just wanting to be sure).

**Comment by mbargull** [comment]
Thanks for the reviews!

**Pull request merged**
