### PR TITLE
In git diff separate revisions and files by --.

### PR DESCRIPTION
**Pull request by vinjana**
I get the following error when using bioconda-utils from the command line and even in simulate_travis.py:

```
$ bioconda-utils lint recipes config.yml --git-range master HEAD
07:56:26 BIOCONDA ERROR COMMAND FAILED: git diff --relative=recipes --name-only master...HEAD recipes/* recipes/*/*
07:56:26 BIOCONDA ERROR STDOUT+STDERR:
fatal: ambiguous argument 'recipes/*': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Traceback (most recent call last):
  File "/home/debian/miniconda3/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils==0.10.0', 'console_scripts', 'bioconda-utils')()
  File "/home/debian/miniconda3/lib/python3.5/site-packages/bioconda_utils/cli.py", line 470, in main
    argh.dispatch_commands([build, dag, dependent, lint, duplicates])
  File "/home/debian/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/home/debian/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/debian/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/debian/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/debian/miniconda3/lib/python3.5/site-packages/bioconda_utils/cli.py", line 255, in lint
    _recipes = select_recipes(packages, git_range, recipe_folder, config_filename, config, force)
  File "/home/debian/miniconda3/lib/python3.5/site-packages/bioconda_utils/cli.py", line 56, in select_recipes
    modified = utils.modified_recipes(git_range, recipe_folder, config_filename)
  File "/home/debian/miniconda3/lib/python3.5/site-packages/bioconda_utils/utils.py", line 863, in modified_recipes
    p = run(cmds, shell=shell)
  File "/home/debian/miniconda3/lib/python3.5/site-packages/bioconda_utils/utils.py", line 179, in run
    raise e
  File "/home/debian/miniconda3/lib/python3.5/site-packages/bioconda_utils/utils.py", line 173, in run
    **kwargs)
  File "/home/debian/miniconda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'diff', '--relative=recipes', '--name-only', 'master...HEAD', 'recipes/*', 'recipes/*/*']' returned non-zero exit status 128
```

The fix is to separate the files from the non-file arguments with "--".

### CODE REVIEW

**Comment by vinjana** [comment]
O.k. now this branch is up to date, but is it worth merging into the opposite direction and update master?

**Comment by daler** [comment]
Thanks @vinjana. Can you clarify your git version? The command

```
git diff --relative=recipes --name-only master...HEAD recipes/* recipes/*/*
```

is working for git 2.13.0, but we had to add some version-specific code here to handle older versions: https://github.com/bioconda/bioconda-utils/blob/533c5553c55cfda0397f444f8a42f7a69712bbd7/bioconda_utils/utils.py#L854.

That said, your fixed version also works fine in 2.13.0 so I think it should be fine to merge.

**Comment by vinjana** [comment]
Just to be 100% certain: The host system of on which simulate_travis.py is being run in relevant, right? Then it works on 2.13.0 and I also have a VM with 2.1.4, which also works.

**Comment by vinjana** [comment]
Thanks!

**Comment by daler** [comment]
Right, the host system does the filtering for what recipes to build; this is done by `bioconda-utils lint` and `bioconda-utils build`. Docker only comes into play when building each individual recipe

**Pull request merged**
