### PR TITLE
fixes https://github.com/bioconda/bioconda-recipes/issues/12988

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by epruesse** [comment]
This is also fixed by aac14fa7d3ffdd5bf3c5628fd4a23963a3f95438 in #382

**Comment by epruesse** [comment]
There was an API change between 4.26 and 4.28 or so. The patch in #382 makes it work with either.

**Comment by johanneskoester** [comment]
Since #382 is merged I guess this can be closed, right?

**Comment by jfallmann** [comment]
Same for #12988 i guess then

**Comment by bgruening** [comment]
I think this can be closed yes. @jfallmann please reopen if you still encounter issues.

**Pull request closed without merging**
