### PR TITLE
add debian link

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by dpryan79** [comment]
What would be the real benefit?

**Comment by epruesse** [comment]
Linking packages with those in Debian. E.g. arb-bio (Bioconda) <-> arb (Debian)

**Comment by dpryan79** [comment]
> Linking packages with those in Debian. E.g. arb-bio (Bioconda) <-> arb (Debian)

Do we actually care about that?

**Comment by bgruening** [comment]
> Do we actually care about that?

Debian cares and the some people in ELIXIR. I think it's a good thing and we try to strengthen our collaboration with Debian and others. More updates in the next meeting :)

Also see here: https://blends.debian.org/med/tasks/bio (search bioconda)

**Pull request merged**
