### PR TITLE
add git to the container

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by epruesse** [comment]
Which one? bioconda-utils-build-dev?
Why?

**Comment by davebx** [comment]
@epruesse Björn and I were discussing how to maybe resolve bioconda/bioconda-recipes#13932 and bioconda/bioconda-recipes#7492

**Comment by epruesse** [comment]
Ah - I see.

**Comment by epruesse** [comment]
It's already in the container.

```console
$ docker run -it bioconda/bioconda-utils-build-env git --version
git version 2.14.2
$ docker run -it bioconda/bioconda-utils-build-env which git
/opt/conda/bin/git
```

Also:
https://github.com/bioconda/bioconda-utils/blob/7672e833367ac3a6238b606a280335ec7ff5b925/bioconda_utils/bioconda_utils-requirements.txt#L23

**Comment by bgruening** [comment]
Meh! Why do people not have git installed then :(

**Pull request closed without merging**
