### PR TITLE
Have linting obey blacklist, modify bioconductor skeleton, fix cleaning of CRAN recipes

### LINKED ISSUE #342: bioconductor-skeleton produced meta.yaml fail linting
Both `conda skeleton cran` and `bioconda-utils bioconductor-skeleton` produced `meta.yaml` files currently set download filenames, which causes linting to fail. Fixing the bioconductor skeleton should be easy enough. Perhaps `bioconda-utils clean-cran-skeleton` could fix the `conda skeleton cran` produced files.

### PR DESCRIPTION
**Pull request by dpryan79**
Fixes #342 among others.

At the moment, `bioconda-utils lint` effectively ignores the blacklist because it's not stripping `recipes/` from recipes paths before checking to see if they're blacklisted (c.f., [this circleci log](https://circleci.com/gh/bioconda/bioconda-recipes/28181)).

This also changes the bioconductor skeleton to add:

    extra:
      skip-lints:
        - should_not_use_fn

The equivalent is now added to CRAN recipes by `bioconda-utils clean-cran-skeleton`. This is related to #316, which apparently we're still seeing even though we're using a `conda-build` version that should be patched (presumably this is a regression).

### CODE REVIEW

**Comment by bgruening** [comment]
@dpryan79 have you tried upgrading to conda-build 3.15.1 (https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/bioconda_utils-requirements.txt#L5). Does this help?

**Comment by dpryan79** [comment]
I've tried 3.15.1, though I can give it another go to be sure.

**Comment by dpryan79** [comment]
Weird, I must have been changing the conda-build version in a different conda environment last night, because now 3.15.1 works for me without the filename stuff. I'll redo a bunch of tests and update recipes and update this PR after further testing (likely Thursday).

**Comment by bgruening** [comment]
Perfect! Thanks @dpryan79 for double checking!

**Comment by dpryan79** [comment]
I've now reverted all of the file name stuff and it seems to work locally.

I suspect a change in the conda API is causing one test to fail. If I start with a clean conda environment and run only `test/test_utils.py::test_skip_dependencies` it succeeds the first time I run it and then fails thereafter. I'll see if I can track down the cause.

**Comment by dpryan79** [comment]
The following commit removed the ability of `conda index` to remove deleted files from the cache, which happened between 3.14.4 and 3.15.0. This is causing the current build failure.

**Comment by dpryan79** [comment]
I've changed one of the tests to simply avoid the new `conda index` behavior.

**Comment by dpryan79** [comment]
Nope, it's not WIP any more, I forgot to change that.

**Comment by dpryan79** [comment]
Relatedly, I'm going to make a small example of the `conda index` issue I mentioned above and open an issue on conda-build.

**Comment by dpryan79** [comment]
Ah, the issue is known https://github.com/conda/conda-build/issues/3167

**Comment by bgruening** [comment]
Thanks @dpryan79! I will pin a release.

**Comment by dpryan79** [comment]
@bgruening Thanks, you'll at the very least need to update bioconda-common to point to the commit hash. I don't actually know if that works, so you might just tag this and then put that tag in bioconda-common.

**Comment by bgruening** [comment]
I know, this was more a question how urgent you want to have it.

**Comment by bgruening** [comment]
Done, both!

**Pull request merged**
