### PR TITLE
Create easybuild easyconfigs from bioconda recipes - WIP

### PR DESCRIPTION
**Pull request by jerowe**
This is a work in progress.

Relates to issue : https://github.com/bioconda/bioconda-recipes/issues/3708

I have the basic skeleton up. I need to add the portion where it actually commits back to github. I have a script that does this somewhere, but I'd like to work on my python skills. ;-)

@boegel this might interest you.

### CODE REVIEW

**Comment by bgruening** [comment]
Do you mind to put this into galaxy-lib. The same place where the docker and singularity magic lives?

**Comment by jerowe** [comment]
No. I was thinking it was a bit outside the scope of the usual bioconda, but I still want it. ;-)

Where is this galaxy-lib?

**Comment by boegel** [comment]
This look cool, I'm sure @fgeorgatos would be a big fan of this...

**Comment by bgruening** [comment]
@jerowe galaxy-lib is here: https://github.com/galaxyproject/galaxy-lib
Here is were all the logic of building Docker/Singularity containers single & multiple ones are located here: https://github.com/galaxyproject/galaxy-lib/blob/master/galaxy/tools/deps/mulled/mulled_build.py

**Comment by jerowe** [comment]
I moved this over to the galaxy lib. I'm trying to get some time to work on this today. My kids are almost back in school!

**Comment by 0xaf1f** [comment]
> I moved this over to the galaxy lib.

@jerowe, do you mean at https://github.com/galaxyproject/galaxy-lib ?
I looked for it there in issues/commits/PRs, but couldn't find it.

**Comment by jerowe** [comment]
By put I mean that I have code sitting on my computer that is 90% ready but I keep getting distracted into making it 100% ready.

You want? People wanting stuff tends to help keep me focused.

**Comment by 0xaf1f** [comment]
> By put I mean that I have code sitting on my computer that is 90% ready but I keep getting distracted into making it 100% ready.

Ah, I see.

> You want? People wanting stuff tends to help keep me focused.

I'm interested in the general idea and whether easybuild is a necessary intermediate step to getting integration with hpc modules.

**Comment by jerowe** [comment]
Its not necessary, its a VERY nice to have.

I could give you many, many details, but I try not to overload these
threads with too many details (aka me and my opinions) unless I get
specifically asked for them. ;-)

**Comment by 0xaf1f** [comment]
Would you mind pushing what you already have now as a work-in-progress PR to wherever you were going to send it?

Is this just a way to create easybuild packages from conda packaging source? Or does it actually use the conda binary packages and have them managed by easybuild?

**Comment by jerowe** [comment]
> Is this just a way to create easybuild packages from conda packaging source? Or does it actually use the conda binary packages and have them managed by easybuild?

Latter. In this case I am using easybuild as a way of deploying my modules, but the software within the modules is built by conda.

**Comment by 0xaf1f** [comment]
That's interesting. Thanks for answering my questions. I'm looking to improve the software management on our cluster, looking between plain easybuild or some conda scheme to work with lmod like what this thread is about. I'll be doing some testing.

**Comment by jerowe** [comment]
Easybuild has great integration with lmod.

I don't know if you are familiar with docker, but I have a bootstrap script
with a docker image around here somewhere to demonstrate to one our sites
how the process would work.

**Comment by jerowe** [comment]
I think this is it -
docker run --rm -t -i quay.io/nyuad_cgsb/easybuild --entrypoint /bin/bash

It will drop you into a docker image with easybuild already installed (from
conda ;-) ).

These are for 'our modules' which are basically just collections of
bioconda/conda software. That is another project besides the
bioconda/easybuild integration, but its related. It will give you a general
idea of how conda envs can be deployed with easybuild anyways.

This converstaion is really itneresting, but getting a bit specific. I'm
very open to talking more, but we should probably move it over to gitter or
email. ;-)

**Comment by 0xaf1f** [comment]
Thanks! I'll take a look when I get a chance and follow up with you through email if I have further questions.

**Pull request closed without merging**
