### PR TITLE
update cf pinning

### PR DESCRIPTION
**Pull request by johanneskoester**
For some reason, all older pinnings have been marked as broken.

### CODE REVIEW

**Comment by johanneskoester** [comment]
cc @mikecormier

**Comment by johanneskoester** [comment]
@bioconda/core, does anybody of you have an insight into the reasoning behind that?

**Comment by dpryan79** [comment]
@bgruening Is this related to the label change? That'd make some sense I guess.

**Comment by dpryan79** [comment]
I think the downstream ramification from this if it's used in `master` is that everything will get built for gcc7/python 3.7 (as is already the case in `bulk`). If we want to forestall that a bit then adding `conda-forge/label/cf20190119` to the channels after conda-forge would be less drastic and not require bioconda dependencies in a PR to be rebuilt.

**Comment by johanneskoester** [comment]
I won't be able to finish this in the next days (teaching and family duties). @dpryan79 your suggestion to temporarilty stick to the old label makes sense to me. If you or anybody else from core would do that, that would be really great! Sorry for not being able to do this myself.

**Comment by dpryan79** [comment]
@johanneskoester No worries, I'll see if I can get this done tonight then.

**Comment by dpryan79** [comment]
I'll close this since we have a temporary solution in place now.

**Pull request closed without merging**
