### PR TITLE
As mentioned on slack, apparently this is sufficient to dissuade a nu…

### PR DESCRIPTION
**Pull request by dpryan79**
…mber of contributions, since the testing can be difficult to setup locally.

### CODE REVIEW

**Comment by dpryan79** [comment]
@pvanheus Do you think this will suffice or would you have other suggestions? We'd obviously like to encourage contributions as much as reasonably possible :)

**Comment by epruesse** [comment]
Which slack? Didn't know we had one. Or did you mean gitter?

**Comment by dpryan79** [comment]
Gah, sorry, I meant gitter.

**Comment by epruesse** [comment]
I'm merging this. @pvanheus - If you guys can come up with better wording - the `edit on github` link on the docs now works as expected and should make it easy to create another PR.

**Pull request merged**
