### PR TITLE
Update HTSLib pinning to 1.9

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by johanneskoester** [comment]
Before merging this @bgruening, is bulk ready for updating htslib-dependent packages? Seems the last commit failed 12 days ago?

**Comment by bgruening** [comment]
@johanneskoester yes bulk should be ready!

**Comment by johanneskoester** [comment]
Ok, released a new version and triggered a bulk rebuild.

I think it would make sense to move our additional pinnings from bioconda-utils to bioconda-common, in order to decouple it from bioconda-utils releases. Any objections against this?

**Comment by johanneskoester** [comment]
Looks like there is no update triggered in bulk, because of the changes to the filtering... So I will have to increase the build numbers manually I guess.

**Comment by johanneskoester** [comment]
@bioconda/core: done, all htslib dependencies have been rebuilt.

**Comment by bgruening** [comment]
Thanks @johanneskoester!

**Pull request merged**
