### PR TITLE
Implement functionality to automatically remove duplicate packages.

### PR DESCRIPTION
**Pull request by johanneskoester**
This does not work due to an anaconda-client bug though :-): we run the correct command, but anaconda-client apparently creates a wrong REST API call.

Before this can be merged, PR #130 has to be merged.

### CODE REVIEW

**Comment by bgruening** [comment]
This you mean with flags, indeed tried that as well and it did not work :(
So manual removal?

**Comment by johanneskoester** [comment]
Yes. I will first implement noarch and then start from the bottom.

**Comment by daler** [comment]
I think you need to explicitly provide the token -- we're already doing this to test uploading: https://github.com/bioconda/bioconda-utils/blob/master/test/test_utils.py#L166

**Comment by johanneskoester** [comment]
Good idea. I will try.

**Comment by johanneskoester** [comment]
Unfortunately, this does not help. It simply seems to use a deprecated URL.

**Comment by daler** [comment]
Ugh, and we are already using the latest anaconda-client. That also means at some point we started accumulating test packages, which will be consuming some space. Prob not much, but non-zero.

**Comment by daler** [comment]
https://anaconda.org/bioconda/repo/files?type=all&label=bioconda-utils-test does not have a big list though, so they are somehow getting deleted

**Comment by bgruening** [comment]
@daler I did this in the morning we were running out of space and did a huge cleanup.

**Comment by daler** [comment]
Ah, never mind, just checked the anaconda.org log and @bgruening did some cleanup a couple of hours ago.

**Comment by daler** [comment]
Thanks! And I just checked gitter, should have checked that before posting here

**Comment by daler** [comment]
According to https://anaconda.org/bioconda/repo/history?page=2&type=all&label=bioconda-utils-test, this seems to have been working as recently as yesterday. Maybe there's something funky going on with the servers today.

**Pull request merged**
