### PR TITLE
Add update scanner

### PR DESCRIPTION
**Pull request by epruesse**
See ~~#345~~ #354

### CODE REVIEW

**Comment by daler** [comment]
@epruesse while I was going through this PR I took some notes and converted them to docs in `updating.rst`. Can you take a look to make sure I understood everything correctly?

**Comment by epruesse** [comment]
@daler *Amazing work* :+1: Thanks a lot for the writeup!

**Comment by epruesse** [comment]
Rebased

**Comment by epruesse** [comment]
@bioconda/core objections to me merging this as well? Far less intrusive than the `channel_dataframe` refactor anyway. 

Do I squash this to keep the commits down, or do I merge normally to preserve history, or do I try and reduce the commit number and merge normally then? (Yes, latter is best, but it'd take so much time..)

**Comment by daler** [comment]
+1 form me on merging, and I'd be fine with normal merge.

**Comment by bgruening** [comment]
Just awesome! :+1:

**Pull request merged**
